PacifidlogTown_House1_EventScript_Girl::
# 2 "data/maps/PacifidlogTown_House1/scripts.pory"
	lock
# 3 "data/maps/PacifidlogTown_House1/scripts.pory"
	faceplayer
# 4 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_EventScript_Girl_Text_0
# 5 "data/maps/PacifidlogTown_House1/scripts.pory"
	release
	return


PacifidlogTown_House1_OldMan::
# 9 "data/maps/PacifidlogTown_House1/scripts.pory"
	lock
# 10 "data/maps/PacifidlogTown_House1/scripts.pory"
	faceplayer
# 11 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_OldMan_Text_0
# 12 "data/maps/PacifidlogTown_House1/scripts.pory"
	release
	return


# 14 "data/maps/PacifidlogTown_House1/scripts.pory"

# 15 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_MapScripts::
# 16 "data/maps/PacifidlogTown_House1/scripts.pory"
	.byte 0
# 17 "data/maps/PacifidlogTown_House1/scripts.pory"

# 18 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Man::
# 19 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
# 20 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 21 "data/maps/PacifidlogTown_House1/scripts.pory"

# 22 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Woman::
# 23 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
# 24 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 25 "data/maps/PacifidlogTown_House1/scripts.pory"

# 26 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_RegiStory:
# 27 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "In the HOENN region, there are three\n"
# 28 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "POKéMON that represent the power of\l"
# 29 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "rock, ice, and steel.\p"
# 30 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Each of them is said to hide away deep\n"
# 31 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "inside caves.\p"
# 32 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "That's the story I heard when I was\n"
# 33 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "just a little kid.$"
# 34 "data/maps/PacifidlogTown_House1/scripts.pory"

# 35 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
# 36 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "“Six dots open three doors.”\p"
# 37 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Grandpa used to say that, but I don't\n"
# 38 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "know what he meant.$"

PacifidlogTown_House1_EventScript_Girl_Text_0:
# 4 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Grandpa told me that people once\n"
	.string "believed Mirage Island only sometimes\l"
	.string "appeared. How silly! It's always been\l"
	.string "just right out there!$"

PacifidlogTown_House1_OldMan_Text_0:
# 11 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "A long time ago, there were many more\n"
	.string "islands in the sea. But ever since\l"
	.string "Kyogre was awoken, most of the land has\l"
	.string "been submerged. You should always be\l"
	.string "grateful that Pacifidlog is built on a\l"
	.string "floating Corsola colony. Most of the\l"
	.string "other cities haven't been so lucky.$"
